### ISSUE TITLE
need mod version info for breaking arg changes

### ISSUE THREAD

**Issue by dallmeyer** [OpenGOAL-Mods/OG-ModLauncher#24]
we need to add a version or something to the json so we know which way to pass the args based on this change:

> Vaser — Today at 21:47
> no rush or anything, just thinking kinda far out. Though once I remove the shim here, gk will break if you run it with args https://github.com/open-goal/jak-project/pull/2189

https://github.com/OpenGOAL-Unofficial-Mods/OpenGoal-ModLauncher-dev/blob/04cc2464881ee52aa6aaa332efff1aa30d183346/utils/launcherUtils.py#L153-L160

**Comment by xTVaser** [comment]
To clarify -- when that PR merges / gets released things shouldn't break.  But my plan is to have one release that's backwards compatible -- which allows launchers to migrate to the new CLI format (without having to release in lock-step with `jak-project`).  However both of us have the same problem -- what if people use old binaries.

For posterity, that's command is basically exactly what the launcher does and the new format would be:
```
gk -v --proj-path <path> -- -boot -fakeiso
```

**Comment by dallmeyer** [comment]
we fixed this at some point?
